import type { TriageArtifact } from "./triage-parser";
import type { Verification } from "./verification";

const MAX_REPRO_ARTIFACT_CHARS = 50_000;
const FOOTER = "*Generated by Repo Butler*";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeInlineCode(value: string): string {
  return escapeHtml(value).replace(/`/g, "\\`");
}

function escapeMarkdownText(value: string): string {
  return escapeHtml(value)
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .split("\n")
    .map((line) =>
      line
        .replace(/^(\s*)([#>*+-])(\s+)/, "$1\\\\$2$3")
        .replace(/^(\s*)(\d+)\.(\s+)/, "$1$2\\\\.$3"),
    )
    .join("\n");
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, "<br />");
}

function formatAreas(areas: string[] | undefined): string {
  if (!areas || areas.length === 0) {
    return "—";
  }

  return areas.map((area) => `\`${escapeInlineCode(area)}\``).join(", ");
}

function formatPatterns(patterns: string[] | undefined): string | null {
  if (!patterns || patterns.length === 0) {
    return null;
  }

  return patterns.map((pattern) => `\`${escapeInlineCode(pattern)}\``).join(", ");
}

function formatSteps(steps: string[] | undefined): string {
  if (!steps || steps.length === 0) {
    return "1. No minimal steps were produced.";
  }

  return steps
    .map((step, index) => `${index + 1}. ${escapeMarkdownText(step)}`)
    .join("\n");
}

function inferCodeFenceLanguage(filePath: string): string {
  const normalizedPath = filePath.toLowerCase();

  if (normalizedPath.endsWith(".py")) {
    return "python";
  }

  if (normalizedPath.endsWith(".ts") || normalizedPath.endsWith(".tsx")) {
    return "typescript";
  }

  if (normalizedPath.endsWith(".js") || normalizedPath.endsWith(".jsx")) {
    return "javascript";
  }

  if (normalizedPath.endsWith(".go")) {
    return "go";
  }

  if (normalizedPath.endsWith(".rb")) {
    return "ruby";
  }

  if (
    normalizedPath.endsWith(".sh") ||
    normalizedPath.endsWith(".bash") ||
    normalizedPath.endsWith(".zsh")
  ) {
    return "bash";
  }

  return "";
}

function truncateArtifactContent(content: string): string {
  if (content.length <= MAX_REPRO_ARTIFACT_CHARS) {
    return content;
  }

  return `${content.slice(0, MAX_REPRO_ARTIFACT_CHARS)}\n\n[truncated to fit GitHub comment limits]`;
}

function buildFooter(dashboardUrl: string): string {
  return `[View full run details](${dashboardUrl})\n\n---\n${FOOTER}`;
}

function buildPolicyChecksDetails(verification: Verification): string | null {
  if (
    verification.verdict !== "policy_violation" &&
    !verification.policy_checks.network_used &&
    !verification.policy_checks.secrets_accessed &&
    !verification.policy_checks.writes_outside_workspace &&
    !verification.policy_checks.ran_as_root
  ) {
    return null;
  }

  return [
    "<details>",
    "<summary>Policy Checks</summary>",
    "",
    `- **Network used:** ${verification.policy_checks.network_used ? "Yes" : "No"}`,
    `- **Secrets accessed:** ${verification.policy_checks.secrets_accessed ? "Yes" : "No"}`,
    `- **Writes outside workspace:** ${verification.policy_checks.writes_outside_workspace ? "Yes" : "No"}`,
    `- **Ran as root:** ${verification.policy_checks.ran_as_root ? "Yes" : "No"}`,
    "",
    "</details>",
  ].join("\n");
}

export function formatTriageComment(
  triage: TriageArtifact,
  dashboardUrl: string,
): string {
  const severity = triage.classification.severity ?? "unknown";
  const confidence = (triage.classification.confidence * 100).toFixed(0);
  const matchPatterns = formatPatterns(
    triage.repro_hypothesis.expected_failure_signal.match_any,
  );

  return [
    "## 🤖 Repo Butler — Triage Summary",
    "",
    "| Field | Value |",
    "|---|---|",
    `| **Type** | ${escapeTableCell(`\`${escapeInlineCode(triage.classification.type)}\``)} |`,
    `| **Severity** | ${escapeTableCell(`\`${escapeInlineCode(severity)}\``)} |`,
    `| **Confidence** | ${confidence}% |`,
    `| **Areas** | ${escapeTableCell(formatAreas(triage.classification.area))} |`,
    "",
    escapeMarkdownText(triage.summary),
    "",
    "<details>",
    "<summary>Reproduction Hypothesis</summary>",
    "",
    `**Expected failure signal:** \`${escapeInlineCode(triage.repro_hypothesis.expected_failure_signal.kind)}\``,
    ...(matchPatterns ? [`**Match patterns:** ${matchPatterns}`] : []),
    "",
    "**Suggested steps:**",
    formatSteps(triage.repro_hypothesis.minimal_steps_guess),
    "",
    "</details>",
    "",
    buildFooter(dashboardUrl),
  ].join("\n");
}

export function formatVerificationComment(
  _triage: TriageArtifact,
  verification: Verification,
  reproArtifact: { file_path: string; content: string } | undefined,
  dashboardUrl: string,
): string {
  const verdictEmoji: Record<Verification["verdict"], string> = {
    reproduced: "✅",
    not_reproduced: "❌",
    flaky: "⚠️",
    policy_violation: "🛑",
    env_setup_failed: "⚠️",
    budget_exhausted: "⏱️",
  };

  const verdictLabel: Record<Verification["verdict"], string> = {
    reproduced: "Reproduction Verified",
    not_reproduced: "Could Not Reproduce",
    flaky: "Flaky Reproduction",
    policy_violation: "Policy Violation",
    env_setup_failed: "Environment Setup Failed",
    budget_exhausted: "Verification Timed Out",
  };

  const sections = [
    `## ${verdictEmoji[verification.verdict]} Repo Butler — ${verdictLabel[verification.verdict]}`,
    "",
    "| Field | Value |",
    "|---|---|",
    `| **Verdict** | ${escapeTableCell(`\`${escapeInlineCode(verification.verdict)}\``)} |`,
    `| **Determinism** | ${verification.determinism.fails}/${verification.determinism.reruns} runs failed |`,
    `| **Flake rate** | ${(verification.determinism.flake_rate * 100).toFixed(1)}% |`,
    `| **Network used** | ${verification.policy_checks.network_used ? "Yes ⚠️" : "No ✓"} |`,
    "",
    escapeMarkdownText(verification.notes ?? "No additional verification notes."),
  ];

  if (
    verification.verdict === "reproduced" &&
    reproArtifact &&
    reproArtifact.file_path &&
    reproArtifact.content
  ) {
    const language = inferCodeFenceLanguage(reproArtifact.file_path);
    const content = truncateArtifactContent(reproArtifact.content).replace(
      /```/g,
      "``\\`",
    );

    sections.push(
      "",
      "<details>",
      `<summary>Reproduction Test — <code>${escapeHtml(reproArtifact.file_path)}</code></summary>`,
      "",
      `\`\`\`${language}`,
      content,
      "```",
      "",
      "</details>",
    );
  }

  sections.push(
    "",
    "<details>",
    "<summary>Failure Evidence</summary>",
    "",
    `- **Command:** \`${escapeInlineCode(verification.evidence.failing_cmd)}\``,
    `- **Exit code:** ${verification.evidence.exit_code}`,
    `- **stderr hash:** \`${escapeInlineCode((verification.evidence.stderr_sha256 ?? "Unavailable").slice(0, 16))}${verification.evidence.stderr_sha256 ? "..." : ""}\``,
    "",
    "</details>",
  );

  const policyChecksDetails = buildPolicyChecksDetails(verification);

  if (policyChecksDetails) {
    sections.push("", policyChecksDetails);
  }

  sections.push("", buildFooter(dashboardUrl));

  return sections.join("\n");
}
