import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const schemasDir = path.join(repoRoot, "schemas");
const outputDir = path.join(repoRoot, "lib", "generated");

async function getSchemaFiles(): Promise<string[]> {
  const entries = await readdir(schemasDir, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name)
    .sort();
}

async function generateSchemaType(schemaFile: string): Promise<void> {
  const schemaPath = path.join(schemasDir, schemaFile);
  const outputPath = path.join(outputDir, schemaFile.replace(/\.json$/, ".d.ts"));
  const types = await compileFromFile(schemaPath, {
    bannerComment: [
      "/**",
      " * This file was generated by `pnpm generate:schema-types`.",
      " * Do not edit this file directly.",
      " */",
    ].join("\n"),
    unreachableDefinitions: true,
  });

  await writeFile(outputPath, `${types.trim()}\n`);
  console.log(`Generated ${path.relative(repoRoot, outputPath)}`);
}

async function main(): Promise<void> {
  const schemaFiles = await getSchemaFiles();

  if (schemaFiles.length === 0) {
    throw new Error("No schema files found in schemas/.");
  }

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  for (const schemaFile of schemaFiles) {
    await generateSchemaType(schemaFile);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
